### ISSUE TITLE
🐞 [BUG]: Display the latest version (e.g 0.0.2-alpha)

### ISSUE THREAD

**Issue by iggy890** [CodeEditApp/codeedit.app#31]
`codeedit.app` does not display the latest CodeEdit version. This could be done with the github api, providing the latest version number.

**Comment by austincondiff** [comment]
Reopening, now it doesn't display at all...

![image](https://user-images.githubusercontent.com/806104/222834595-fd0e1749-b0ca-4986-a176-1c1d177d2e7e.png)

**Comment by iggy890** [comment]
Happening with me, but only on the website not with `npm run dev`.

**Comment by iggy890** [comment]
For some mysterious reason this is now fixed: 
<img width="181" alt="shot" src="https://user-images.githubusercontent.com/98705626/222902128-e24690dc-8271-42cc-93c5-c8d07710c84a.png">
